

# =============== 1.) Switch Modules =============
# Aktiviert oder deaktiviert die Module, die für die Auswertung der Daten verwendet wird

modules:
  run_descriptive_statistics: true   # Module: Descriptive Statistics
  run_test_statistics: true         # Module: Test Statistics
    # run_t_test oder so
  run_time_analysis: true            # Module: Time-dependent analysis
    # run_survival ?
  run_missing_values: true          # Module: Missing Values
  
  
# =============== 2.) Input Data & Output Dir =============
# data:
#  input_file: "path/to/your/input_data.csv"  
#  output_report: "output/report/"     
